### ISSUE TITLE
Missing configuration 'ColinAct'

### ISSUE THREAD

**Issue by dwhan89** [msyriac/orphics#9]
I tried to run tests/testSNAct.py, but it was missing the configuration 'ColinAct'. I attached the error message below. 

```
dwhan89@cori01:~/cori/workspace/orphics> python tests/testSNAct.py 
Generating theory Cls...
WARNING:root:accuracy parameters are changed globally, not yet per parameter set
Traceback (most recent call last):
  File "tests/testSNAct.py", line 21, in <module>
    ls,Nls,ellbb,dlbb,efficiency = lensNoise(Config,expName,lensName,beamOverride=None,noiseTOverride=None,lkneeTOverride=None,lkneePOverride=None,alphaTOverride=None,alphaPOverride=None)
  File "/global/u2/d/dwhan89/cori/workspace/pyfisher/pyfisher/lensInterface.py", line 8, in lensNoise
    beam = listFromConfig(Config,expName,'beams')
  File "/global/u2/d/dwhan89/cori/workspace/orphics/orphics/tools/io.py", line 124, in listFromConfig
    return [float(x) for x in Config.get(section,name).split(',')]
  File "/global/common/cori/software/python/2.7-anaconda/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'ColinACT'

```

**Comment by msyriac** [comment]
Should work now if "iniFile" points to the right file in pyfisher. I shared this script just so you could read off how to get errorbars, didn't really intend it to work out of the box. Check out
https://github.com/msyriac/orphics/blob/master/tests/testSN.py

where I've made a simpler to read and commented description of how you can get theory errors for Clkk.

Replace the planck Nlkk file with whatever Nl curve you want.
